### ISSUE TITLE
Issue preventing editor from being called

### ISSUE THREAD

**Issue by kyuhyunIm** [tinymce/tinymce#10670]
Currently, I'm calling the editor through the @tinymce/tinymce-react module. However, for some reason, starting around 4 PM, the editor call is failing and it's impossible to initialize. What could be the reason?

**Comment by Ruskwolfe** [comment]
Same issue across all my platforms

**Comment by MikaLeppiaho** [comment]
This has happened to me as sell with just "Failed to load resource: the server responded with a status of 504 () from tinymce.min.js:1"

**Comment by ShaunWilders** [comment]
We pay for and rely on this for our ticket system and currently can't reply to anything. All their own demos aren't working either at tiny.cloud.

**Comment by dpbyrne** [comment]
I'm seeing bad gateway errors accessing tinymce.min.js from the cdn. 

Alos not able to sign into account

**Comment by wjsrbgus04** [comment]
It seems like there's been an AWS server outage. Could this be related?

https://www.theverge.com/news/802486/aws-outage-alexa-fortnite-snapchat-offline

**Comment by lajuffermans** [comment]
It's AWS, see: https://status.tiny.cloud/

...perhaps someone knows an alternative CDN URL?

**Comment by abiynne** [comment]
Same issue facing, even with the no api link as well .

URL attempted: https://cdn.tiny.cloud/1/<API_KEY>/tinymce/6/tinymce.min.js

Public test link https://cdn.tiny.cloud/1/no-api-key/tinymce/6/tinymce.min.js also fails.

Browser console shows ReferenceError: tinymce is not defined.

Network tab shows 502 Bad Gateway / No healthy upstream.

**Comment by Ruskwolfe** [comment]
> It seems like there's been an AWS server outage. Could this be related?
> 
> https://www.theverge.com/news/802486/aws-outage-alexa-fortnite-snapchat-offline

Gonna say this is probably it.

**Comment by mohamedds-12** [comment]
It seems that it has been fixed.

**Comment by lostkeys** [comment]
Yes, There was a massive AWS outage earlier today affecting a large part of the internet. All Tiny's services are back to normal now.

— Fredrik, Product Manager

**Comment by kacperporebski** [comment]
Still getting 503 in production and testing as mentioned by a user above.

> Same issue facing, even with the no api link as well .
> 
> URL attempted: https://cdn.tiny.cloud/1/<API_KEY>/tinymce/6/tinymce.min.js
> 
> Public test link https://cdn.tiny.cloud/1/no-api-key/tinymce/6/tinymce.min.js also fails.
> 
> Browser console shows ReferenceError: tinymce is not defined.
> 
> Network tab shows 502 Bad Gateway / No healthy upstream.

Is this a new outage or unresolved issue from previous outage?

**Comment by RalphK66** [comment]
Also getting 503
This must be a new issue.
