### ISSUE TITLE
getContent() in 'change' handler breaks toolbar buttons

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2180]
Description of problem:
Calling getContent() in a handler of the 'change' event breaks (visually) toolbar buttons. It's a _getter_ method, which shouldn't mutate any state.

Steps to reproduce:
1. Bind a handler to the 'change' event of the editor. In this handler call editor.getContent()
2. Click the "B" (bold) button on the toolbar

Expected result:
After the click, the button should become to appear pressed.

Actual result:
The button appears like it's not pressed until some content is typed in.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7469](http://archive.tinymce.com/develop/bugtracker_view.php?id=7469) posted by [thorn](http://archive.tinymce.com/profile.php?name=thorn)_

> _**Tags:** [chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/9Jeaab_

**Comment by spocke** [comment]
Fixed this issue. The getContent call shouldn't modify the UI it modifies the state of the document and then the UI picks up on that. It's when pending formats are marked as bogus so I had to add an extra bogus type "format" that is kind of bogus but still visible by UI related checks.

**Comment by ianmclean2011** [comment]
@spocke, I'm still seeing this issue. Do you happen to know what release this made it into, and perhaps what PR? Thanks!
