### ISSUE TITLE
Safari 9.0.2 forces scroll to bottom of page on drag select

### ISSUE THREAD

**Issue by Ian-Webb** [tinymce/tinymce#2557]
In version 9.0.2 of Safari, when a TinyMCE editor instance has enough content to fill the container (and, therefore, has a scroll bar), clicking the mouse and dragging to select causes the browser window to immediately (before releasing the mouse) scroll to the bottom of the page.

This appears to be happening on all instances of TinyMCE, across various websites, but only in Safari 9.0.2 - Safari 9.0.1 is not affected.

Although this is plainly a Safari bug caused by Apple's update, getting Apple to fix anything not security-related is usually glacial at best, so do you think there is a patch that can be applied to TinyMCE to eliminate the problem please?

**Comment by spocke** [comment]
Hmm, couldn't reproduce this this is what I did:

1. Opened https://www.tinymce.com
2. Pressed enter a few times at the end of the text to produce a scrollbar.
3. Selected some contents.
4. Observer that no scrolling occured.

This was on Safari: Version 9.0.2 (11601.3.9) OS X El Captian.

**Comment by Ian-Webb** [comment]
Hi Spocke!

Thanks for getting back to me. At first, I couldn't get this behaviour to appear on tinymce.com either, but I found that if I reduced the height of the browser so that the Tour and Download buttons are cut off, it does scroll down.

It seems to be a combination of the height of the page, the height of the browser, the length of the content and the height of the TinyMCE editor window - weird!

Could you try it again please? I've attached a screenshot showing tinymce.com in my browser - this triggers it every time.

Although, in this instance, the browser is unusually shallow, I have Admin pages that are very long and have several editors, which trigger this issue even with a browser window 1200px deep.

Cheers, Ian.

<img width="1166" alt="screen shot 2015-12-15 at 13 50 10" src="https://cloud.githubusercontent.com/assets/16304645/11812272/d764f4a8-a332-11e5-9942-84d4593d2f06.png">

**Comment by spocke** [comment]
Not sure we can fix this I reported this to WebKit:
https://bugs.webkit.org/show_bug.cgi?id=152332

If affects any iframe not only TinyMCE and there is no way to block scroll events that I'm aware of. So they need to fix it and a.s.a.p.

**Comment by Ian-Webb** [comment]
Hi Spoke!

Yeah I thought that might be the case. Thanks for reporting it to Webkit.

Cheers, Ian.

**Comment by lcenvs** [comment]
Would appreciate staying in the loop on this, as it affects me and my students using TinyMCE editor e.g. on our WordPress multisite...thanks, Jim P.

**Comment by spocke** [comment]
Good news WebKit has fixed the problem:
https://bugs.webkit.org/show_bug.cgi?id=152332

So we just have to wait for Apple to release a fix.

**Comment by zocoloco** [comment]
Glad to see this is in the process of being fixed! It's been driving me crazy for months. Hopefully Apple will release a fix soon!

**Comment by brandonbest** [comment]
Very annoying issue. Thank you spocke for looking into it for us. Looking forward to Apple releasing Safari updates!

**Comment by JasonTheAdams** [comment]
Using 9.0.3 and the problem still persists. Hope they update webkit soon.

**Comment by zocoloco** [comment]
Same here...using 9.0.3 and still having scroll issues. Doesn't happen on textareas (like the field I'm writing in now) - just TinyMCE iFrames.

**Comment by spocke** [comment]
It's been reported to Apple and fixed in their nightlies. So we just have to wait. This affects any iframe not only TinyMCE. Also there is no way for us to fix it since there is no preventDefault() for the scroll event.

**Comment by zocoloco** [comment]
thanks for the update @spocke

**Comment by Josheua** [comment]
I can confirm this issue remains present in both iOS 10.3.2 and 10.3.3 Beta 3.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
