### ISSUE TITLE
media_dimensions option breaks the plugin

### ISSUE THREAD

**Issue by CurtisConway** [tinymce/tinymce#3446]
https://jsfiddle.net/5r7zsn5q/

Here's a barebones fiddle of the configuration I'm trying run. As you can see I have the media_dimensions option set to false, and if you try to embed a video you get an error "Media embed handler threw unknown error".

If you go and change that media_dimensions option to true, you no longer get the error and it works as intended.

**Comment by fyrkant** [comment]
Fixed in yesterdays 4.5.3 release.

**Comment by dev-101** [comment]
https://jsfiddle.net/yfckh75f/

Not sure about 4.5.3, but in 4.5.5 this still does not seem to be working properly.

Try to embed iframe:
`<iframe width="560" height="315" src="https://www.youtube.com/embed/1YhJQVutNA8" frameborder="0" allowfullscreen></iframe>`

Now, click on Source Code button and dimensions will be set to "undefined". This is a regression since 4.5.1 (and older), because, as per my understanding, this should only hide dimension input boxes in the media plugin, but if they are present in the embed source link, they should be kept.

**Comment by spocke** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.
