### ISSUE TITLE
Backspace/Del deletes whole document on Chrome

### ISSUE THREAD

**Issue by pavel-j** [tinymce/tinymce#3493]
When I select part of text and press Del, whole document is deleted sometimes (frequently).
TinyMCE 4.5.3, occurs even in demo at www.tinymce.com

Reproducing:
When I insert HTML source bellow, to demo editor at www.tinymce.com,
- then, select text from HR to end of document (selection starts immediately above HR)
- and press Del (or Backspace), entire document is deleted in about 50% cases

Chrome latest version, windows 10.

HTML source used to reproduce:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv=Content-Type content="text/html; charset=utf-8" eq=".keephead,.keepstyle,.keepmeta">
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<style>
body,td{font-family:Arial,sans;font-size:10pt;}
p{margin:0.5em 0;}
ul,ol{margin-top:0.5em;margin-bottom:0.5em;}
li{margin-top:0;margin-bottom:0.5em;}
table{border-collapse:collapse}
img{outline:none;text-decoration:none;-ms-interpolation-mode:bicubic;border:none;}
</style>
</head>

<body>
<p>Dobr&yacute; den pan&iacute; Hor&aacute;kov&aacute;,</p>
<p>zas&iacute;l&aacute;m potvrzen&yacute; dobropis</p>
<div id="signature">
<p>&nbsp;</p>
<p><span style="color: #333399;"><span style="font-family: 'courier new', courier, monospace;">------------------------------------------<br />Ing. Pavel Jel&iacute;nek<br />Astra Systems, s.r.o.<br />Tel. 776 103&nbsp;600<br />Tel. 245 009 411<br /></span><a style="font-family: 'courier new', courier, monospace; color: #333399;" href="mailto:pavel.jelinek@deleted.dd">pavel.jelinek@deleted.dd</a></span></p>
</div>
<p><br /><br /></p>
<div style="border-top: 1px solid #B5C4DF; padding-top: 3px;"><strong>Od:</strong> Jelinek Pavel &lt;Pavel.Jelinek@deleted.dd&gt;<br /><strong>Odesl&aacute;no:</strong> 17.02.2017 11:13<br /><strong>Komu:</strong> pavel.jelinek@deleted.dd &lt;pavel.jelinek@deleted.dd&gt;<br /><strong>Předmět:</strong> FW: Naskenovano na multifunkcnim zarizeni Xerox</div>
<p>&nbsp;</p>
<div style="font-family: 'Lucida Console',monospace; font-size: 10pt;">
<p style="margin: 0;">________________________________________</p>
<p style="margin: 0;">Odes&iacute;late: xerox@nexa.cz [xerox@deleted.dd]</p>
<p style="margin: 0;">Odesl&aacute;no: 17. &uacute;nora 2017 11:09</p>
<p style="margin: 0;">Komu: Jelinek Pavel</p>
<p style="margin: 0;">Předmět: Naskenovano na multifunkcnim zarizeni Xerox</p>
<p style="margin: 0;">&nbsp;</p>
<p style="margin: 0;">Otevrete prilozeny dokument.&nbsp;&nbsp;Tento dokument byl naskenovan a odeslan pomoci multifunkcniho zarizeni Xerox.</p>
<p style="margin: 0;">&nbsp;</p>
<p style="margin: 0;">Typ př&iacute;lohy: pdf, V&iacute;ce stran</p>
<p style="margin: 0;">&nbsp;</p>
<p style="margin: 0;">Um&iacute;stěn&iacute; multifunkčn&iacute;ho zař&iacute;zen&iacute;: recepce</p>
<p style="margin: 0;">N&aacute;zev zař&iacute;zen&iacute;: Xerox WorkCentre 7220</p>
<p style="margin: 0;">&nbsp;</p>
<p style="margin: 0;">&nbsp;</p>
<p style="margin: 0;">Dalsi informace o produktech a resenich spolecnosti Xerox ziskate na adrese http://www.xerox.com.</p>
</div>
</body>
</html>
```

I also noted this problem in comment of (closed) issue #3459.
Because of its severity, I rather created new issue.

**Comment by fyrkant** [comment]
@pavel-j Can you test this again with the newest TinyMCE version (4.5.4)? It should have been fixed in that.

**Comment by pavel-j** [comment]
It seems to be solved. Thank you

**Comment by pavel-j** [comment]
Hello, unfortunately, problem is not solved completely (as of 4.5.4). 
Sometimes, Del still deletes entire document, instead of selected paragraph.

It doesn't occur as frequently as in 4.5.3. 
Worse, I can no longer reproduce it in tinymce demo. It occurs only sometimes
- previously, with specific HTML, it was always reproducible
- now, when i get document deleted and use the same HTML again, it works OK second time.

**Comment by spocke** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.
