### ISSUE TITLE
Accent keys (´`) on mceNonEditable bug

### ISSUE THREAD

**Issue by ghost** [tinymce/tinymce#3641]
**Do you want to request a *feature* or report a *bug*?**

I want to report a Bug

**What is the current behavior?**

When i insert a ´or ` accent in a div with mceNonEditable class, this is permitted unlimited times

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.

Steps to reproduce

1. Created a div with mceNonEditable class and some characteres inside.
2. Try to edit.
3. press ´or ` key

**What is the expected behavior?

The div has to be non editable

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

I work with TinyMCE version ~4.2.1, on Chrome and Mac OS.

**Comment by spocke** [comment]
Does it happen on the latest version of tinymce 4.6.0 I think this might have been fixed since.

**Comment by Dvdor** [comment]
in tinymcs 4.6.1, I still have the error in this code when i type a ´ ` (accent key ) in the mceNon Editable cell.

<table class="mceNonEditable">
<tr>
    <td class="mceNonEditable">
        Contents
    </td>
  </tr>  
<tr>
    <td class="mceEditable">
        Contents
    </td>
  </tr>
</table>

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
