### ISSUE TITLE
modern/theme.js IIFE broken with 4.7.5?

### ISSUE THREAD

**Issue by anx-ckreuzberger** [tinymce/tinymce#4164]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
There seems to be an issue with theme.js with the latest release 4.7.5 with the IIFE.
I get this error when trying to include theme.js
```
theme.js:2 Uncaught TypeError: (intermediate value)(...) is not a function
    at theme.js:2
```
Where theme.js is located here:
node_modules/tinymce/themes/modern/theme.js

The error does not appear with version 4.7.4.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
4.7.5

**Comment by fyrkant** [comment]
Are you using tinymce with a module bundler, including it with an `import` or `require`?

**Comment by anx-ckreuzberger** [comment]
Yes, kind of.
I am bundling the following modules into a "deps.js" file:
```html
    <!-- tinymce -->
    <script src="node_modules/tinymce/tinymce.js"></script>
    <!-- Plugins (make sure to include all tinymce plugins that you need, and test this with a production build) -->
    <script src="node_modules/tinymce/themes/modern/theme.js"></script>
    <script src="node_modules/tinymce/plugins/image/plugin.js"></script>
    <script src="node_modules/tinymce/plugins/charmap/plugin.js"></script>
    <script src="node_modules/tinymce/plugins/textpattern/plugin.js"></script>
    <script src="node_modules/tinymce/plugins/advlist/plugin.js"></script>
    <script src="node_modules/tinymce/plugins/autolink/plugin.js"></script>
    <script src="node_modules/tinymce/plugins/link/plugin.js"></script>
    <script src="node_modules/tinymce/plugins/lists/plugin.js"></script>
    <script src="node_modules/tinymce/plugins/autoresize/plugin.js"></script>
    <script src="node_modules/tinymce/plugins/textcolor/plugin.js"></script>
    <script src="node_modules/tinymce/plugins/colorpicker/plugin.js"></script>
    <script src="node_modules/tinymce/plugins/hr/plugin.js"></script>
    <script src="node_modules/tinymce/plugins/table/plugin.js"></script>
```
Though I believe that tinymce still tries to access the files (like "node_modules/tinymce/themes/modern/theme.js") even though it has access to the bundled files.

**Comment by ldrick** [comment]
Hi there, seems closely related to my issue #4165

**Comment by ChristianKreuzberger** [comment]
@ldrick quite possible, yes.

**Comment by fyrkant** [comment]
@ChristianKreuzberger 
Can you try installing tinymce nightly like this:
```sh
npm install http://download.ephox.com/tinymce/community/tinymce_nightly.tgz
```
And see if it's working better?

**Comment by fyrkant** [comment]
This has been fixed in 4.7.6 that was released today so I'm closing this, if you still have a problem just leave a comment and I can open it again.

**Comment by mistic100** [comment]
Hi,

I think the problem still exists, the dist files still not having a final ";"
when the files are concatenated with grunt-uglify, the output file is not parseable.

You can read this SO question which explain why it is a good practice to _start_ with a semicolon in case a library (here tinymce) do it wrong.
https://stackoverflow.com/questions/7145514/whats-the-purpose-of-starting-semi-colon-at-beginning-of-javascript

In this specific case, tinymce neither have the start or end semicolon and the problem appears when bundling tinymce.js with the theme.js

**Comment by mistic100** [comment]
I am locked to 4.7.4 for now (we are in the process in migrating to webpack which will eliminate this kind of error, but currently we are stuck to grunt)

**Comment by fyrkant** [comment]
@mistic100 So you are having this problem on 4.7.4? Then I think it is a separate issue, this problem was caused by some changes we did for 4.7.5.

**Comment by mistic100** [comment]
No, it works in 4.7.4 that why I had to lock my version.
The problem was indeed introduced in 4.7.5

**Comment by AndreMarthaler** [comment]
Hi.

The problem exists on 4.7.6 too.
Getting same error after updated from 4.7.4 to 4.7.6

Version 4.7.4 works fine.

**Comment by fyrkant** [comment]
@mistic100 and @AndreMarthaler 

Can you reproduce the problem you are having? How are you bundling the files?

**Comment by AndreMarthaler** [comment]
I use gulp and pump to bundle it together.

if i switch back to 4.7.4 in package.json and rebuild it, it works fine.
Attached you will find error message.

Hopefully it helps.

Andre.

![tinymce_error](https://user-images.githubusercontent.com/7644642/35562789-cc8e789c-05b4-11e8-800a-c070a1a56434.png)

**Comment by fyrkant** [comment]
Thank you @AndreMarthaler I found where I need to fix it and it will be fixed in the next release but until then you can use the minified files  - `tinymce.min.js`, `plugin.min.js`, `theme.min.js` - and that should work.

**Comment by asaarnak** [comment]
I have similar issue only on 4.7.5 and 4.7.6, works on 4.7.4.

Works great on 4.7.5 and 4.7.6 also if i don't uglify and just import:
tinymce/tinymce.js
tinymce/themes/modern/theme.js
angular-ui-tinymce/src/tinymce.js

I'm using latest gulp for concating all js lib files into 1 big js lib file.
And then latest gulp-uglify v3.0.0.
![tinymce-4 7 5-4 7 6-issue](https://user-images.githubusercontent.com/808420/35702555-19e7d6f8-07a2-11e8-9cba-dc67db39bfe0.png)

**Comment by mistic100** [comment]
When is the fix planned ?
IMHO this is as much critical as the previous fix for webpack.

**Comment by fyrkant** [comment]
@mistic100 I think this has been fixed in the latest 4.7.6 release, maybe you can try it out and report back?

**Comment by asaarnak** [comment]
Actually i tested on 4.7.6, still exists.
https://github.com/tinymce/tinymce/issues/4164#issuecomment-362401021

**Comment by fyrkant** [comment]
Yeah sorry I misspoke, 4.7.7 will be released soon with the fix in it.

**Comment by fyrkant** [comment]
But like I said above, if you import the `.min.js` files I think it should work already.

**Comment by asaarnak** [comment]
Yep, but our script needs unminified .js, because we concat all libs and then minify ourselves.

**Comment by fyrkant** [comment]
I don't think it makes a difference if the files are already minified when you concat them?

**Comment by asaarnak** [comment]
Actually it makes difference in the speed and i think not so big in minification itself also, as the minification algorithms are not used to already minifed files.

**Comment by asaarnak** [comment]
The error dissapeared on 4.7.7.

**Comment by anx-ckreuzberger** [comment]
Confirmed, works with 4.7.7. Thanks everybody.
