### ISSUE TITLE
[V5.0.0 p1-b.6] Tiny main menu only partly visible in inline mode

### ISSUE THREAD

**Issue by Georg-Git** [tinymce/tinymce#4599]
**bug**

After Init of Tiny in **Inline Mode** only the lower part the main menue is visible.

See:
https://jsfiddle.net/6m8kzqju/36/
press button "Init Tiny Inline"

After setting cursor inside the editor area the full menue becomes visible.

In classic mode display of the main menue is correct.

**Comment by TheSpyder** [comment]
Ah, we missed that one. Thanks for the report!

Hopefully by release we have improved the logic to move the toolbar below the editor when it won't fit, as TinyMCE 4 does.

**Comment by lnewson** [comment]
@Georg-Git this issue appears to have been fixed by the time 5.0 reached stable, but before I close this I just wanted to double check it's fixed for you?

**Comment by Georg-Git** [comment]
First:
Thank You very much for Your efforts in communication with tiny users.
Big improvements in the last year!

In the last days I became more familiar with Your changes in tiny 5.

I still have a problem with positioning of the tiny menu in inline mode when the html text to edit starts on top of the page:
http://fiddle.tinymce.com/FCgaab/2

But You promised the fixed_toolbar_container will come back soon.

The other thing is a bug in the table plugin.
You made some improvements in the table plugin for version 5.x, but this is not fixed. 
See also in the fiddle example.

**Comment by Georg-Git** [comment]
In the the new fiddle environment things apear different than in real live.

But when I try the same example on jsfiddle.net the effects are the same than in my real environment:
https://jsfiddle.net/sr0eav71/

**Comment by TheSpyder** [comment]
That difference is because the cloud uses more well-tested releases than the "edge" option on `fiddle.tinymce.com` which links to nightly builds from github master. If you use `tinymce5-cloud-stable` it will be the same as your jsfiddle.

We are planning to release version 5.0.1 to cloud next week, I believe.

**Comment by Georg-Git** [comment]
I am not  talking about the different tiny releases.

The behavior of fiddle on tinymce.com is different.
In had used on both sides the same code and for example fix the height of the div container to 200px.

After init of tiny in inline mode on Your side the height is overreided.
But this correlated only to your fiddle setup.

On jsfiddle.net the behavior of the editor is correct and like in real live environment.

**Comment by Georg-Git** [comment]
[5.0.2] fixed_toolbar_container is back - now I have no problems with tiny menu:

Only for the records:
Behavior of tiny inside Your fiddle setup on tinymce.com is still different to real live environment.
E.g. height of div container is overrided:

http://fiddle.tinymce.com/FCgaab/3
