### ISSUE TITLE
Link list content displays offscreen when page is scrolled towards bottom

### ISSUE THREAD

**Issue by cdaveb** [tinymce/tinymce#4624]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When scrolled towards the bottom of the page, the link_list feature when using nested menus does not correctly adjust the position of the menus to the edge of the browser window, so menu content flows outside the window and is not usable.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

I've created an example here of the behavior:
https://codepen.io/cdaveb/pen/YJERby

To reproduce it, bring up the link window by selecting text and using the link option. Then scroll towards the bottom of the page. Open the link list and navigate the menus. You'll note that some of the menus appear cutoff by the edge of the page. This can be worked around by scrolling upwards, but it's not a good user experience and the workaround isn't obvious. Below is a screenshot of the behavior in question:

![link_list_example](https://user-images.githubusercontent.com/6133808/46982385-e6bfd600-d090-11e8-9194-49927986698f.png)

**What is the expected behavior?**

The expected behavior is for the menus to be displayed in a position that the entire menu can be seen or scrolled to, even when at the bottom of the screen. In other spots on the page the menu is shifted upwards, but this doesn't seem to happen when scrolled towards the bottom of the page.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

I'm not sure how far back the issue goes. I can reproduce it in 4.8.0 and 4.8.3 in Chrome and Firefox on the Mac .

**Comment by lnewson** [comment]
This should now be fixed, as of version 4.8.5.

**Comment by cdaveb** [comment]
This helped, but it did not completely fix the issue. I can still reproduce this issue with smaller window sizes in TinyMCE 4.9.3. I have updated my original CodePen to reference 4.9.2 since that is the highest version available on the cloud from what I can find:
[https://codepen.io/cdaveb/pen/YJERby](url)

This is a screenshot of what I'm seeing:
![tinymce_scrollsoffscreen](https://user-images.githubusercontent.com/6133808/52749652-b0428b00-2f9e-11e9-8707-7b98debf1f79.png)

The main issue seems to be that it is still possible if the top level menu is long and the window is small (best way to reproduce this is to create a small browser window), that it will display partly offscreen, without any kind of scrollbar to allow you to access the full list of items. In addition, when this happens, the submenus can also end up cutoff at the edge of the screen.

I have confirmed the problem still exists in both Chrome and Firefox on Mac.

**Comment by lnewson** [comment]
So what looks to be happening here, is that there's not enough room for the menu to display at all, so it can't position itself above or below and just falls back to the default position.

**Comment by lnewson** [comment]
As per my comment on #4827 the above is actually a different issue, so I'm going to close this again and open #4827 because this was about it not working when scrolled at the bottom of the page and as per the screenshot, you can see the window is scrolled near the top of the page.
