### ISSUE TITLE
Spacebar not working properly

### ISSUE THREAD

**Issue by colinmathews** [tinymce/tinymce#4685]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The user cannot insert a space under certain configurations. Pressing the spacebar once does nothing and pressing it again inserts two spaces.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
http://fiddle.tinymce.com/34gaab

**What is the expected behavior?**
User hits the spacebar and a single space is added,.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
This works in 4.8.5. It breaks in 4.9.0

**Comment by lukejsimonetti** [comment]
I have the same problem after upgrading to 4.9.0.

**Comment by benoitongit** [comment]
Same issue here too. Works with v4.8.5 but breaks with v4.9.0.

**Comment by fyrkant** [comment]
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.

**Comment by Daijobou** [comment]
Sure this is fixed?
Changelog said for version 4.9.1

> Fixed a bug where the space bar didn't work correctly in editors with the forced_root_block setting set to false. #TINY-2816

I upgrade from 4.8.5 to 4.9.1 and few users reporting now issues with spacebar in chrome (android). I can reproduce it too in android chrome browser. Chrome on PC (desktop) working fine for me.

**Comment by AdrianStoichita** [comment]
It's still broken on Chrome. On Mozilla everything works smoothly

**Comment by miketemby** [comment]
Issue still exists but appears to be more specific now. First line typed has no problems but once I return, adding a break into the string, the second line space characters do not work. 
Using Chrome on desktop.

**Comment by brunoniconeves** [comment]
The problem persists on Chrome like @miketemby  said

**Comment by freeman-g** [comment]
For anyone using the cloud.tinymce.com cdn, I've changed my link from

`https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=<api key>`

to

`https://cloud.tinymce.com/4.8.5/tinymce.min.js?apiKey=<api key>`

to resolve the issue for now

**Comment by jasonfah** [comment]
4.9.2 also still broken.

http://fiddle.tinymce.com/G6gaab

Steps to replicate:
1. enter the text 'test:' then press ENTER
2. enter the text 'test' then press ENTER
3. enter the text 'test' then press SPACEBAR
4. Note that nothing happens...

**Comment by miketemby** [comment]
As @jasonfah said above. 4.9.2 still has this issue. 
Using CDN.

Third line, spaces stopped working. 

![image](https://user-images.githubusercontent.com/41090032/50134747-99a4ee00-02e5-11e9-948f-78ba6eb83464.png)

**Comment by Nickproger** [comment]
I tested on different version:
fixed on 4.9.3 and on 5.0.0

**Comment by developerPaul84** [comment]
Stilling having the issue on our website, user can type into a text area fine until the 3rd or 4th line, seems to be happening on chrome only, anyone else tested on 4.9.3 or 5.0.0 and are there any breaking changes in the updates?

**Comment by arnaudbey** [comment]
hey there. tested with the 5.0.0 release and it fixed the problem for me on chrome

**Comment by BrendanTRyan** [comment]
I have just encountered this problem as described most recently bt DeveloprPaul84. It manifests on the 4th line entered. I am running Wordpress "version 5.1.1–en_AU" I had not previousely experienced this glitch as some had in previous versions. It seems to occur if i am using Shift+Enter to reduce line spacing. But from what i can tell it seems not to happen if just using enter with regular line spacing.
Classic Editor enabled - Gutenberg not active.
Black Studio TinyMCE Widget Version 2.6.8
TinyMCE Advanced version 5.1.0
cHROME CURRENT Version 73.0.3683.103 (Official Build) (64-bit)

**Comment by ragesoss** [comment]
I was running into very similar problems today, and ultimately found that it was caused by CSS: the editor was inheriting `white-space: pre-line`, which causes trailing whitespace to not register on Chrome (but not on Firefox).

**Comment by CleanSoftwareIsKey** [comment]
I'm having the same problem on Chrome & this is right after the WP update yesterday. Vs. 5.2.

I had to save as draft every few words of text.

Why hasn't this bug been fixed already? It dates back to 2016 :(

**Comment by BrendanTRyan** [comment]
One way to trick it, is once you get to the third line - enter a period- then move the cursor back before the period. It then types fine registering spacebar spaces as normal. It seems that typing, where your enter point is before the last character in the line, is not affected by the spacebar glitch. Certainly not a fix. Just a variation on the symptom.

**Comment by spocke** [comment]
@BrendanTRyan @CleanSoftwareIsKey Are you having the same CSS issue as @ragesoss that is something I could confirm and logged internally.

Also @CleanSoftwareIsKey What 2016 bug are you referring to this bug was opened 2018?

**Comment by DenisSemionov** [comment]
Is this going to be fixed?

**Comment by CleanSoftwareIsKey** [comment]
@spocke - no clue the name of the bug, I did a search & this was a bug back in 2016, so I guess it came back somehow.

**Comment by BrendanTRyan** [comment]
> @BrendanTRyan @CleanSoftwareIsKey Are you having the same CSS issue as @ragesoss that is something I could confirm and logged internally.
> 
> Also @CleanSoftwareIsKey What 2016 bug are you referring to this bug was opened 2018?

I am only experiencing this in Chrome. I have not ventured into Firefox or other browsers to view it. For me  if Chrome has the issue, the other Browsers are secondary. So I am not much help in verifying if it is Browser specific issue.

**Comment by spocke** [comment]
Just to clarify the only fix we are working on at the moment is for the white-space: pre-line css issue that @ragesoss was having that will likely land very soon in nightly builds/cloud dev channel. If that isn't the issue you are experiencing then we need more details on how to reproduce that particular issue some fiddle or similar.

**Comment by CleanSoftwareIsKey** [comment]
@BrendanTRyan - I'm on Chrome too.
@spocke - No clue what you are talking about. The subject of this thread is that the spacebar isn't working, so that's why I added to this thread.

I haven't had the problem since that day, but I haven't done any posting since then & now I can't remember which blog it was LOL

Thanks

**Comment by pculka** [comment]
we just encountered the same problem. Chrome only and after an "return" the spacebar starts to suddenly work on first press. When returning to previous line, a double tap on spacebar is needed and it produces 2 spaces at once.
Firefox is OK.

**Comment by wonderbugtiny** [comment]
The `white-space: pre-line` CSS issue that @ragesoss was having has been fixed in TinyMCE 5.0.6.
If you are facing any other issues related to this ticket we request that you please make a new ticket. Thank you!

**Comment by Daijobou** [comment]
Is this issue fixed in 4.x too?

**Comment by lixpng** [comment]
> Is this issue fixed in 4.x too?

We upgrad to 4.9.8, and the issue exist too. But it only happen in some of our user's computer, we don't know how to reappear it.

**Comment by BrendanTRyan** [comment]
Your version is still

> > Is this issue fixed in 4.x too?
> 
> We upgrad to 4.9.8, and the issue exist too. But it only happen in some of our user's computer, we don't know how to reappear it.

I think you should update to current versions. This topic seemed to be resolved using later builds than you seem to be using. Wordpress on 5.4 and I use TinyMCE Advanced 5.4.0.

**Comment by lixpng** [comment]
> Your version is still
> 
> > > Is this issue fixed in 4.x too?
> > 
> > 
> > We upgrad to 4.9.8, and the issue exist too. But it only happen in some of our user's computer, we don't know how to reappear it.
> 
> I think you should update to current versions. This topic seemed to be resolved using later builds than you seem to be using. Wordpress on 5.4 and I use TinyMCE Advanced 5.4.0.

Yea, we are planing to upgrade to 5.x.

**Comment by Silencer-1984** [comment]
> 我今天遇到了非常类似的问题，最终发现它是由CSS引起的：编辑器是继承的`white-space: pre-line`，这导致结尾的空白无法在Chrome（但不能在Firefox）上注册。

If the `white-space:  pre-line` does this, then the space is not converted to `'&nbsp;'`. Cannot save space

**Comment by ILoveSkilledCoders** [comment]
> > 我今天遇到了非常类似的问题，最终发现它是由CSS引起的：编辑器是继承的`white-space: pre-line`，这导致结尾的空白无法在Chrome（但不能在Firefox）上注册。
> 
> If the `white-space: pre-line` does this, then the space is not converted to `'&nbsp;'`. Cannot save space

WTF ????

**Comment by djbclark** [comment]
Could a kind soul point me to the way to verify this is the bug I am seeing under dev channel ChromeOS? My thought was maybe code injection but perhaps there is a more canonical way? 

https://stackoverflow.com/questions/67547338/force-tinymce-into-plain-text-mode-or-specific-version-everywhere-in-chrome-via

**Comment by djbclark** [comment]
FYI since this is only a TinyMCE issue in my case if there is a regression, I opened this bug: 

https://bugs.chromium.org/p/chromium/issues/detail?id=1214045

Issue 1214045: Spacebar doesn't work in some rich text entry boxes on some ChromeOS devices.
