### ISSUE TITLE
TinyMCE 5: Menu items wrapped when menu has a scroll & formatted menu items have invalid HTML

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#4768]
Steps:
1. Goto https://www.tiny.cloud/rc/
2. Make the window height small
3. Click on the font selector

If the fonts list has a scrollbar, some font names are wrapped. In Firefox, not in Chrome.

**Comment by alecpl** [comment]
BTW, the code like this is not valid HTML:
```
<span class="tox-collection__item-label">
    <div style="font-family:arial black,sans-serif">Arial Black</div>
</span>
```

**Comment by blackcathikari** [comment]
The menu width problems might be related to and fixed by #4821. Linking the issues so I can check back later.

**Comment by lnewson** [comment]
This should now be fixed in 5.0.2, as the menu items now use a div for the label instead of a span. Please let us know if you find any further problems!

**Comment by alecpl** [comment]
@lnewson Spans became divs, but the wrapping issue is not fixed.

**Comment by lnewson** [comment]
Right you are sorry, I missed that this had multiple issues in the one report. I'll follow up and make sure we have a task logged for the other issue as well.

**Comment by alecpl** [comment]
Still an issue in 5.2.0.
