### ISSUE TITLE
'url' dialogs not supported in v5 (External file managers compatibility issue)

### ISSUE THREAD

**Issue by Draghmar** [tinymce/tinymce#4786]
Hi.
I'm trying the all new and shiny v5 but I've noticed there is some huge issue in terms of compatibility with integrations for file management that were using `tinyMCE.activeEditor.windowManager.open`. Most of them (if not every one of them) was simply loading html file into iframe provided by tinyMCE popup. But now with the new UI Dialog that won't work.

So what's the proper solution to get the same result?

I found that the new UI Dialog has an [`Iframe`](https://www.tiny.cloud/docs-beta/ui-components/dialogcomponents/#iframe) component so I thought that maybe that's the one...but the truth is I have no idea what is the reason for this component to exists. You can't set `src` and applying anything at `initialData` just add it as a text into body of created iframe. So the result gives similar experience to the `HtmlPanel` _(Yup, I can even insert html this way)_.
And even if I take the random `ID` of the created iframe and force `src` to take the URL *I want* I can't do anything because of the enforced dimensions. So...what's the point of this component? Am I missing something here?

![obraz](https://user-images.githubusercontent.com/275348/51595951-2865e580-1ef8-11e9-82e5-dd4bbc67f8f0.png)

**Comment by Draghmar** [comment]
Yeah, I've noticed that. But the two questions are still open:
1. What's the point of `iframe` component when it behaves very similar to the `HtmlPane` component?
2. Does that mean there's no way of integrating external file manager with tinyMCE? And you have to rely on external way to popup the content? _I can do this but it's an additional hassle that previous version was taking care of_

**Comment by TheSpyder** [comment]
The `iframe` component exists primarily because of the preview plugin, it has to load content CSS so the preview renders correctly which wouldn't work in a `htmlpane`.

You're right, `htmlpane` is very similar, we have considered excluding it from the release. It's only used by the help plugin at the moment.

The new UI in TinyMCE 5 is a wide scale change, we are aware this is disruptive and are keeping an eye on the feedback to see what we need to address and how quickly.

**Comment by Draghmar** [comment]
Yeah...This change will break many external plugins that uses iframe and html to get some advanced things done. As a another example I'm using [tinymce-plugin-youtube](https://github.com/gtraxx/tinymce-plugin-youtube) to insert movies because that was the easiest way to put iframe in a tag I wanted and not in `p` like tinyMCE does by default. In v5 it doesn't work for the same reason...But maybe in v5 it would be easier to achieve that using native methods but I didn't check that part yet, it would great though.

**Comment by martyf** [comment]
This is a current roadblock for me too - and have been looking at how to achieve it using the new Dialog and UI Components, but am stuck now - hence issue #4783.

**Comment by sbillard** [comment]
This is a deal breaker for me. I need to get a PHP script to run to properly populate my dialog. Note that my plugin is NOT a file manager. Rather it is a tool for inserting cropped images from the application. Sort of a cut and paste support but with options.

**Comment by mutekellim** [comment]
> I've solved this issue by following,

 file_picker_callback: FileManager // tinymce option


```
function FileManager(callback, value, meta) {
        var windowManagerURL = "/FilManage";// filemanager path
 
        var windowManagerCSS = '<style type="text/css">' +
            '.tox-dialog { transition: max-width linear 0.2s; max-width: 100%!important; width:97.5%!important; overflow: hidden; height:95%!important; border-radius:0.25em;}' +
            '.tox-dialog__header{ display:none!important; }' +
            '.tox-dialog__footer { display: none!important; }' +
            '.tox-dialog__body { padding: 0!important; }' +
            '.tox-dialog__body-content > div { height: 100%; overflow:hidden}' + 
            '</style > ';
        window.tinymceCallBackURL = '';
        window.tinymceWindowManager = tinymce.activeEditor.windowManager;
        tinymceWindowManager.open({
            title: '',
            body: {
                type: 'panel',
                items: [{
                    type: 'htmlpanel',
                    html: windowManagerCSS+ '<iframe src="' + windowManagerURL + '"  frameborder="0" style="width:100%; height:100%"></iframe>'
                }]
            },
            buttons: [] ,
            onClose: function () {
                if (tinymceCallBackURL!='')
                    callback(tinymceCallBackURL, {}); //to set selected file path
            } 
          
        } );
    }
```


//In FileManage
```
var windowManager = top != undefined && top.tinymceWindowManager != undefined ? top.tinymceWindowManager : '';


 if (windowManager != '') {
        if (top.tinymceCallBackURL != undefined)
            top.tinymceCallBackURL = path;
            windowManager.close();
    }
```

**Comment by sbillard** [comment]
Thanks much. I have fitted your example to my plugin. It is working great in tinyMCE4, so onward to the migration of netPhotoGraphics to use tinyMCE5.

**Comment by gtraxx** [comment]
@Draghmar Hi, I'm looking to update my youtube plugin :)

**Comment by TheSpyder** [comment]
Not long, now...

https://github.com/tinymce/tinymce-docs/pull/1021

**Comment by lnewson** [comment]
We've just released 5.0.4, which includes the ability to create URL dialogs again! A couple things to note however, is that we've moved the URL dialog functionality to it's own API: `editor.windowManager.openUrl(spec)` and we've removed the `file` configuration setting as it's been replaced by `url`. Please let us know if you have any further questions.

Note: The docs aren't yet available for the URL dialogs sorry, but should be live in ~2 weeks. The docs PR @TheSpyder mentioned above though contains the details for the new API.

**Comment by vanillajonathan** [comment]
`editor.windowManager.openUrl` is still not mentioned in the documentation.

**Comment by vanillajonathan** [comment]
URL dialogs are now supported using the `editor.windowManager.openUrl` function.

I solved it this way:

```js
tinymce.init({
    selector: 'textarea.tinymce',
    file_picker_callback: function(callback, value, meta) {
        tinymce.activeEditor.windowManager.openUrl({
            title: 'File Manager',
            url: '/filemanager?type=' + meta.filetype,
            onMessage: function (api, data) {
                if (data.mceAction === 'customAction') {
                    callback(data.url);
                    api.close();
                }
            }
        });
    },
});
```

Then in the file manager:
```js
function insert(url) {
    window.parent.postMessage({
        mceAction: 'customAction',
        url: url
    }, '*');
}
```
and call the insert function:
```html
<img src="cat.jpg" onclick="insert('cat.jpg')" />
```

**Comment by gtraxx** [comment]
@Draghmar Hi, test youtube plugin for tinymce 5 : https://github.com/gtraxx/tinymce-plugin-youtube/tree/tinymce5 :)

**Comment by martyf** [comment]
It's worth noting that the new URL Dialog UI component gives so much more than just an iframe and a quick fix for old plugins. I think Tiny did a great job at providing not only iframe support but a framework to allow for some really cool potential for advanced plugins.

The messaging between the iframe and your Tiny instance (i.e. your plugin code) is so powerful now, it is a great opportunity to also ensure that interfaces are upgraded to match user experience expectations (including quality of UI) and code cleaned up to follow the revised conventions for URL Dialogs and messaging capabilities, be that simple, command-based or custom.

The [Tiny docs](https://www.tiny.cloud/docs/ui-components/urldialog/) are incredibly useful, and I've also got [some working demos](https://www.martyfriedel.com/blog/tinymce-5-url-dialog-component-and-window-messaging).
