### ISSUE TITLE
AddOnCallback Type Misuse

### ISSUE THREAD

**Issue by tmitch0** [tinymce/tinymce#5321]
Custom plugins added with the AddOnManager.add function have 'new' called on them. The AddOnCallback type should be updated to convey the expectation that 'new' will be called on whatever is passed in. When arrow functions are passed in that are valid AddOnCallback types, TinyMce fails to load the plugin since the plugin "is not a constructor"

http://fiddle.tinymce.com/IXgaab

https://github.com/tinymce/tinymce/blob/6f823b481e6cc360e7a8f3bf5b6bf9f7174592a4/modules/tinymce/src/core/main/ts/init/Init.ts#L40

**Comment by lnewson** [comment]
Thanks for reporting this! Coincidentally we actually found this out internally a couple weeks ago ourselves, so it's has already been fixed in our internal 5.2 development branch.

**Comment by minspy** [comment]
> Thanks for reporting this! Coincidentally we actually found this out internally a couple weeks ago ourselves, so it's has already been fixed in our internal 5.2 development branch.

why in tinymce `5.5.1` still had this problem?

**Comment by vitexikora** [comment]
Issue persists in 5.10, had to change the plugin function to an ordinary one (from arrow function).

The error was exactly `Plugin is not a constructor`, for anyone looking this up.
